on: push
    jobs:
        build-node:
            runs-on: ubuntu-latest
            container: node:14
            steps:
                - run: node --versiion
                - run: npm --version
                - uses: actions/checkout@v3
                - run: npm install
                - run: node index.js