on:
  push:
    branches:
      - main
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Check out code
            uses: actions/checkout@v2
          - name: Run a one-line script
            run: echo Hello, world!
          - name: Run another script
            run: echo This is another script.
